# .github/labeler.yml

# Define label rules based on branch names
branches:
  - label: "type: chore"
    pattern: 
      - '/chore\/.+/'
      - '/refactor\/.+/'
      - '/maintenance\/.+/'

  - label: "type: fix"
    pattern:
      - '/fix\/.+/'
      - '/hotfix\/.+/'
      - '/bugfix\/.+/'
      - '/patch\/.+/'

  - label: "type: feature"
    pattern:
      - '/feat\/.+/'
      - '/feature\/.+/'
      - '/enhancement\/.+/'
      - '/new\/.+/'

  - label: "type: docs"
    pattern:
      - '/doc\/.+/'
      - '/docs\/.+/'


# Define label rules based on file names
files:
  - label: "type: chore"
    pattern:
      - "*.yml"
      - "*.conf"
      - "*.sbt"
      - "*.json"
      - "*.xml"
      - "Dockerfile"

  - label: "type: docs"
    pattern:
      - "*.md"
      - "*.txt"
      - "*.rst"
      - "*.wiki"
      - "*.html"


# Define label rules based on pull request titles
titles:
  - label: "type: chore"
    pattern:
      - /chore/i
      - /refactor/i

  - label: "type: fix"
    pattern:
      - /fix/i
      - /hotfix/i
      - /bugfix/i
      - /patch/i

  - label: "type: feature"
    pattern:
      - /feat/i
      - /feature/i
      - /enhancement/i
      - /new/i

  - label: "type: docs"
    pattern:
      - /doc/i
      - /docs/i
