"type: docs": ['/doc\/.+/','/docs\/.+/']
- any:
  - changed-files:
    - any-glob-to-any-file: ["*.md","*.txt","*.rst","*.wiki","*.html"]

"type: chore": ['/chore\/.+/', '/refactor\/.+/','/maintenance\/.+/']
- any:
  - changed-files:
    - any-glob-to-any-file: ["*.yml","*.conf","*.sbt","*.json","*.xml","Dockerfile"]
  - head-branch: ['/chore\/.+/', '/refactor\/.+/','/maintenance\/.+/']

"type: feature": ['/feat\/.+/','/feature\/.+/','/enhancement\/.+/','/new\/.+/']
"type: fix": ['/fix\/.+/','/hotfix\/.+/','/bugfix\/.+/','/patch\/.+/']
