# .github/labeler.yml
feature:
 - branches:
     - '/feat\/.+/'
   titles:
     - /feat/i
 - branches:
     - '/feature\/.+/'
   titles:
     - /feature/i
 - branches:
     - '/enhancement\/.+/'
   titles:
     - /enhancement/i
 - branches:
     - '/new\/.+/'
   titles:
     - /new/i

fix:
 - branches:
     - '/fix\/.+/'
   titles:
     - /fix/i
 - branches:
     - '/hotfix\/.+/'
   titles:
     - /hotfix/i
 - branches:
     - '/bugfix\/.+/'
   titles:
     - /bugfix/i
 - branches:
     - '/patch\/.+/'
   titles:
     - /patch/i

docs:
 - branches:
     - '/doc\/.+/'
   titles:
     - /doc/i
 - branches:
     - '/docs\/.+/'
   titles:
     - /docs/i

chore:
 - branches:
     - '/chore\/.+/'
   titles:
     - /chore/i
 - branches:
     - '/refactor\/.+/'
   titles:
     - /refactor/i
 - branches:
     - '/maintenance\/.+/'
   titles:
     - /maintenance/i
