# .github/labeler.yml

# Define label rules based on branch names
branches:
  - label: feature
    pattern: feature/*
  - label: bug
    pattern: bug/*
  # Add more branch-based rules as needed

# Define label rules based on pull request titles
titles:
  - label: enhancement
    pattern: /\[ENHANCEMENT\]/
  - label: documentation
    pattern: /\[DOCS\]/
  # Add more title-based rules as needed
