name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main
  push:
    branches:
      - "**"
      
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
             const fs = require('fs');
             const content = fs.readFileSync('helo.txt', 'utf8');
              const commits = context.payload.commits;
                const lastCommit = commits[commits.length - 1];
              const pullRequests = lastCommit.associatedPullRequests;
              const issue_number = pullRequests && pullRequests.length > 0 ? pullRequests[0].number : context.issue.number;
               const owner = context.repo.owner;
             const repo = context.repo.repo;
             github.issues.createComment({
               issue_number: 19,
               owner: owner,
               repo: repo,
               body: content
             });
