name: Comment on PR

on:
 push:
   branches:
     - main

jobs:
 comment:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Comment PR
       uses: actions/github-script@v3
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         script: |
           const { owner, repo } = context.repo
           const pullRequests = await github.pulls.list({
             owner,
             repo,
             state: 'open',
             head: `${owner}:${github.context.ref}`
           })
           if (pullRequests.data.length > 0) {
             const pr = pullRequests.data[0]
             await github.issues.createComment({
               owner,
               repo,
               issue_number: pr.number,
               body: 'This is a comment on PR'
             })
           }
