name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main
  push:
    branches:
      - "**"
      
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Install dependencies
        run: cargo build --verbose

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = github.event.before; // Use before or after commit hash as a reference to find associated pull request
            const body = 'Hello! This is a comment on the associated pull request.';
            const response = await github.issues.createComment({ owner, repo, issue_number: prNumber, body });
            console.log(response);
