name: Add Comment on PR

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main
  push:
    branches:
      - "**"
      
jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Add comment to PR
        run: |
          COMMENT="Hello! This is an automated comment on your pull request."
          echo "$COMMENT" | gh pr comment ${{ github.event.before }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
