name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main
  push:
    branches:
      - "**"
      
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const commitSha = github.sha;

            // Fetch the pull request associated with the commit
            const { data: pulls } = await github.pulls.list({
              owner,
              repo,
              head: `${owner}:${commitSha}`,
            });

            // Check if there is at least one pull request
            if (pulls.length > 0) {
              const prNumber = pulls[0].number;
              const body = 'Hello! This is a comment on the associated pull request.';
              const response = await github.issues.createComment({ owner, repo, issue_number: prNumber, body });
              console.log(response);
            } else {
              console.log('No associated pull request found.');
            }
