name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main
  push:
    branches:
      - "**"
      
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Comment on PR
        run: |
          const axios = require('axios');

          const { owner, repo } = context.repo;
          const commitSha = github.sha;

          try {
            const response = await axios.get(
              `https://api.github.com/repos/${owner}/${repo}/commits/${commitSha}/pulls`
            );

            if (response.data.length > 0) {
              const prNumber = response.data[0].number;
              const body = 'Hello! This is a comment on the associated pull request.';
              await axios.post(
                `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`,
                { body },
                {
                  headers: {
                    Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                  },
                }
              );
            } else {
              console.log('No associated pull request found.');
            }
          } catch (error) {
            console.error('Error fetching pull request:', error.response ? error.response.data : error.message);
            process.exit(1);
          }
