name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main
  push:
    branches:
      - "**"
      
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: machine-learning-apps/pr-comment@1.0.0
        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           comment-file:  benches/iai-callgrind/benchmarks.cfg # replace with the path to your file
