name: File Workflow

on:
  push:
    branches:
      - main

jobs:
  Cache_Benchmarks:
    name: Cache Micro Benchmarks result
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Benchmarks
        run: |
          cargo install cargo-criterion rust-script
          cargo criterion --message-format=json > benches/main_benchmarks.json
          ./scripts/json_to_md.rs benches/main_benchmarks.json > benches/main_benchmarks.md
          cat benches/main_benchmarks.md

      - name: Cache Criterion Benchmarks Json
        uses: actions/cache@v4
        with:
          path: benches/main_benchmarks.json
          key: criterion_benchmarks_${{ github.sha }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: json-artifact
          path: benches/main_benchmarks.json

  Track_Benchmark:    
    name: Track Benchmark with Bencher
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    needs: Cache_Benchmarks
    env:
      BENCHER_PROJECT: tailcall
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: json
      BASE_BENCHMARK_RESULTS: benches/main_benchmarks.json
    steps:
      - name: Download Text File
        uses: actions/download-artifact@v4
        with:
          name: json-artifact

      - name: Convert Artifact
        run: |
          cat benches/main_benchmarks.json | jq -s 'map(select(.id and .mean and .slope and .median) | {id: .id, mean: .mean, slope: .slope, median: .median})' > benches/track_benchmark.json
      
      - uses: bencherdev/bencher@main
      - name: Track base Benchmarks
        run: |
          export BENCHER_API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhcGlfa2V5IiwiZXhwIjoxNzIwMDYyMTI4LCJpYXQiOjE3MTAwNjIxMjgsImlzcyI6ImJlbmNoZXIuZGV2Iiwic3ViIjoiZGFicmFsYWxhbmtyaXRAZ21haWwuY29tIiwib3JnIjpudWxsfQ.0QUtYqWgPtyYV8d6SsK2m4hNoa88r6aSI6Ojupatd3s
          bencher run \
          --branch 'main' \
          --ci-id '${{ github.event.pull_request.number }}' \
          --github-actions "${{ secrets.GITHUB_TOKEN }}" \
          --err \
          --file "$BASE_BENCHMARK_RESULTS"
