name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  benchmark:
    name: Macro Benchmarks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Comment Content
        run: |
          touch benches/comment_content.txt
          echo "Main Benchmarks:" > benches/comment_content.txt
          cat benches/a.md >> benches/comment_content.txt

      - name: Comment on Commit
        run: |
           gh pr review ${{ github.event.number }} --comment --body-file benches/comment_content.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

