name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  benchmark:
    name: Macro Benchmarks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Comment on Pull Request
        run: |
          gh pr comment ${{ github.event.number }} --body "Here are the benchmark results:" --path benches/benchmark.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

