name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  benchmark:
    name: Macro Benchmarks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Read file content
        id: readfile
        run: echo "::set-output name=content::$(cat benches/a.md)"


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
 
      - name: Create comment
        uses: peter-evans/create-pull-request-comment@v2  # Update to the correct version if available
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.event.repository.full_name }}
         pull-request-number: ${{ github.event.pull_request.number }}
         body: |
           File content:
           ```
            ${{ steps.readfile.outputs.content }}
 
