name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  benchmark:
    name: Macro Benchmarks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Print File Content
        run: cat benches/a.md
        id: print-content

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: benches/a.md
          vars: |
            foo: this
            bar: that

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          pull-request-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.print-content.outputs.stdout }}${{ steps.template.outputs.result }}
          reactions: '+1'
