name: Comment on PR
on: [pull_request]

jobs:
 comment:
   runs-on: ubuntu-latest
   steps:
     - name: Comment on PR
       uses: actions/github-script@v5
       with:
         script: |
           const issue_number = context.issue.number;
           const comment = 'This is a comment from the CI pipeline';
           github.rest.issues.createComment({
             owner: context.repo.owner,
             repo: context.repo.repo,
             issue_number: issue_number,
             body: comment
           });
