name: Benchmarks and build time

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  runBenchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install criterion-compare-action
        run: |
          mkdir -p ~/.cargo/bin
          curl -LsSf https://github.com/boa-dev/criterion-compare-action/releases/download/v3.2.4/critcmp -o ~/.cargo/bin/critcmp
          chmod +x ~/.cargo/bin/critcmp

      - name: Run benchmarks and comment on PR
        if: github.event_name == 'pull_request'
        run: |
          # Run benchmarks
          critcmp base changes

          # Comment on the pull request
          output=$(critcmp base changes)
          echo "$output"
          awk 'NR > 2 {
              group=$1
              base=$7
              changes=$3

              gsub(/[^\-0-9\.]/, "", changes)
              gsub(/[^\-0-9\.]/, "", base)

              if (changes != "" && base != "") {
                  diff = changes - base
                  percentage = (diff / base) * 100

                  if (percentage > 10) {
                      printf "Percentage change for %s exceeds 10%%: %.2f%%\n", group, percentage
                      exit 1
                  }
              }
          }' <<< "$output" | \
          if [[ $? -eq 0 ]]; then
              COMMENT="Benchmarks Passed! :white_check_mark:"
          else
              COMMENT="Benchmarks Failed! :x:"
          fi
          echo "$COMMENT"
          echo "::set-output name=COMMENT::$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        run: |
          COMMENT="${{ needs.runBenchmarks.outputs.COMMENT }}"
          echo "Comment: $COMMENT"
          echo "$COMMENT" | gh pr comment ${{ github.event.number }} --body -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#asf