name: Call a reusable workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
 call-workflow:
   uses: alankritdabral/tailcall/.github/workflows/job1.yml

 call-workflow-passing-data:
   permissions:
     contents: read
     pull-requests: write
   uses: alankritdabral/tailcall/.github/workflows/job2.yml
   with:
     config-path: .github/labeler.yml
   secrets:
     token: ${{ secrets.GITHUB_TOKEN }}
