name: "Pull Request Labeler"

on:
  pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Run Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
         
      # label based on PR title
      - uses: github/issue-labeler@v3.3
        with:
          configuration-path: .github/pr_label.yml
          include-title: 1
          include-body: 0
          enable-versioned-regex: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

  remove-unused-labels:
    runs-on: ubuntu-latest
    needs: labeler
    steps:
      - name: Get current labels
        run: |
          current_labels=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/labels" | \
            jq -r '.[].name')
          echo "Current labels: $current_labels"
      
      - name: Remove unused labels
        run: |
          unused_labels="chore docs fix feature"
          for label in $unused_labels; do
            if [[ ! "$current_labels" =~ "$label" ]]; then
              echo "Removing label: $label"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/$label"
            fi
          done
