name: "Pull Request Labeler"

on:
  pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5

    # label based on PR title
    - uses: github/issue-labeler@v3.3
      with:
        configuration-path: .github/pr_label.yml
        include-title: 1
        include-body: 0
        enable-versioned-regex: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.3 #May not be the latest version
      with:
        configuration-path: .github/pr_label.yml
        include-body: 0
        enable-versioned-regex: 0
        repo-token: ${{ github.token }}
