name: "Pull Request Labeler"

on:
  pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Run Labeler
        uses: actions/labeler@v5
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         sync-labels: true
         
    # label based on PR title
      - uses: github/issue-labeler@v3.3
        with:
          configuration-path: .github/pr_label.yml
          include-title: 1
          include-body: 0
          enable-versioned-regex: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

      - name: Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            type: chore
            type: docs
            type: fix          
            type: feature
        env:
          CURRENT_LABELS: ${{ steps.labeler.outputs.all-labels }}
