name: "Pull Request Labeler"

on:
  pull_request_target

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            "type: chore"
            "type: docs"
            "type: fix"           
            "type: feature"

  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5

    # label based on PR title
    - uses: github/issue-labeler@v3.3
      with:
        configuration-path: .github/pr_label.yml
        include-title: 1
        include-body: 0
        enable-versioned-regex: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}
