name: Label Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add labels
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: |
          - name: "type: chore"
            pattern: |
              chore
              refactor
              maintenance
          - name: "type: fix"
            pattern: |
              fix
              hotfix
              bugfix
              patch
          - name: "type: feature"
            pattern: |
              feat
              feature
              enhancement
              new
          - name: "type: docs"
            pattern: |
              doc
              docs
        files: |
          - "*.yml"
          - "*.conf"
          - "*.sbt"
          - "*.json"
          - "*.xml"
          - "Dockerfile"
          - "*.md"
          - "*.txt"
          - "*.rst"
          - "*.wiki"
          - "*.html"
