name: Label Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
       toolchain: stable
       override: true

    - name: Build and run Rust script
      run: |
       cargo install cargo-criterion rust-script
       rust-script scripts/label_pr
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
