# .github/workflows/labeler.yml
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
 labeler:
   permissions:
     contents: read
     pull-requests: write
   runs-on: ubuntu-latest
   steps:
   - uses: actions/labeler@v5
   - uses: TimonVS/pr-labeler-action@v4
     with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      configuration-path: .github/labeler.yml
