name: Auto Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auto labeler
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
