name: multiple ci benchmarks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  run_multiple_benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run json_like_bench
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
        uses: boa-dev/criterion-compare-action@v3.2.4
        with:
          benchName: json_like_bench
          defaultFeatures: false
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run impl_path_string_for_evaluation_context
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
        uses: boa-dev/criterion-compare-action@v3.2.4
        with:
          benchName: impl_path_string_for_evaluation_context
          defaultFeatures: false
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run data_loader_bench
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
        uses: boa-dev/criterion-compare-action@v3.2.4
        with:
          benchName: data_loader_bench
          defaultFeatures: false
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run request_template_bench
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
        uses: boa-dev/criterion-compare-action@v3.2.4
        with:
          benchName: request_template_bench
          defaultFeatures: false
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add a step to analyze benchmark percentage differences
      - name: Check Benchmark Changes
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
        run: |
          # Assign the benchmark results to a variable
          benchmark_results=$(/home/runner/.cargo/bin/critcmp base changes) # Replace with the command to fetch the benchmark results

          # Parsing the benchmark results and checking for percentage differences
          echo "$benchmark_results" | awk 'NR > 1 { print $1, $2, $3, $4, $6, $7 }' | while read -r group base changes; do
              if [[ "$changes" == "?" || "$base" == "?" ]]; then
                  continue
              fi
              base=$(echo "$base" | sed 's/.*[[:space:]]//') # Extracting the base value
              changes=$(echo "$changes" | sed 's/.*[[:space:]]//') # Extracting the changes value

              percentage=$(echo "scale=2; (($changes - $base) / $base) * 100" | bc) # Calculating percentage difference

              # Checking if the percentage change exceeds 10%
              if [ $(echo "$percentage > 10" | bc) -eq 1 ]; then
                  echo "Percentage change for $group exceeds 10%: $percentage%"
                  exit 1 # Exiting with a non-zero status to indicate a CI failure
              fi
          done
