name: Micro benchmarks

on:
  push:
    branches:
      - "**"

jobs:
  Micro-benchmarks:
    if: contains(github.event.pull_request.labels.*.name, 'benchmark') || contains(github.event.head_commit.message, 'benchmark')
    name: criterion_benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Critcmp
        run: cargo install critcmp

      - name: Create temporary directory
        run: temp_dir=$(mktemp -d)

      - name: Copy compare_build_time.sh to temporary directory
        run: cp .github/scripts/compare_build_time.sh "$temp_dir/.github/scripts/"

      - name: Benchmark changes
        run: |
          bash "$temp_dir/.github/scripts/compare_build_time.sh"

      - name: Cleanup temporary directory
        run: rm -rf "$temp_dir"

      - name: Fetch base branch
        run: git fetch

      - name: Checkout base branch
        run: git checkout ${{ github.base_ref }}

      - name: Benchmark base
        run: |
          cargo bench --bench impl_path_string_for_evaluation_context -- --save-baseline main_branch
          cargo bench --bench data_loader_bench -- --save-baseline main_branch
          cargo bench --bench request_template_bench -- --save-baseline main_branch
          cargo bench --bench json_like_bench -- --save-baseline main_branch

      - name: Run shell script
        run: |
          chmod +x .github/scripts/check_degradation.sh
          .github/scripts/check_degradation.sh

      - name: Debug Info
        run: |
          echo "Owner: ${{ github.repository_owner }}"
          echo "Repo: ${{ github.repository }}"
          echo "Issue Number: ${{ github.event.number }}"

      - name: Comment PR
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const fileContent = fs.readFileSync('benches/criterion/benchmarks.txt', 'utf8');
            const issue_number = context.issue.number;
            const comment = `
            <details>
            <summary>Benchmark Results</summary>
            | Test                          | Base         | PR               | % change   |
            |-------------------------------|--------------|------------------|------------|
            ${fileContent}
            </details>
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment
            });

  Build_time_compare:
    if: contains(github.event.pull_request.labels.*.name, 'benchmark') || contains(github.event.head_commit.message, 'benchmark')
    name: iai_callgrind_benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from the repository
        uses: actions/checkout@v2

      - name: Install iai-callgrind-runner
        run: cargo install --version 0.7.3 iai-callgrind-runner

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install valgrind

      - name: Execute build_time_compare.sh
        run: |
          chmod +x .github/scripts/compare_build_time.sh
          bash .github/scripts/compare_build_time.sh
