name: Comment Criterion

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Critcmp
      run: cargo install critcmp

    - name: Benchmark changes
      run: |
        cargo bench --bench impl_path_string_for_evaluation_context -- --save-baseline new_branch
        cargo bench --bench data_loader_bench -- --save-baseline new_branch
        cargo bench --bench request_template_bench -- --save-baseline new_branch
        cargo bench --bench json_like_bench -- --save-baseline new_branch

    - name: Fetch base branch
      run: git fetch

    - name: Checkout base branch
      run: git checkout ${{ github.base_ref }}

    - name: Benchmark base
      run: |
        cargo bench --bench impl_path_string_for_evaluation_context -- --save-baseline main_branch
        cargo bench --bench data_loader_bench -- --save-baseline main_branch
        cargo bench --bench request_template_bench -- --save-baseline main_branch
        cargo bench --bench json_like_bench -- --save-baseline main_branch
    - name: Run critcmp and add PR comment
      run: |
        output=$(/home/runner/.cargo/bin/critcmp main_branch ${{ github.event.before }})

        comments=$(awk 'BEGIN {
            comment=""
        }
        NR > 2 {
            group=$1
            base=$7
            changes=$3

            gsub(/[^\-0-9\.]/, "", changes)  # Extract only numerical values
            gsub(/[^\-0-9\.]/, "", base)     # Extract only numerical values

            # Ensure changes and base values are not empty
            if (changes != "" && base != "") {
                diff = changes - base  # Calculate the absolute difference
                percentage = (diff / base) * 100  # Calculate the percentage difference

                if (percentage > 10) {
                    comment = comment sprintf("Percentage change for %s exceeds 10%%: %.2f%%\n", group, percentage)
                }
            }
        }
        END {
            print comment
        }' <<< "$output")

        echo "$output"

        if [ -n "$comments" ]; then
            echo "Adding comments to the pull request:"
            echo "$comments"

            pr_number="${{ github.event.number }}"

            curl -X POST \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments" \
                -d "{\"body\":\"$comments\"}"
        fi
    - name: Comment on PR
      uses: actions/github-script@v5
      with:
          script: |
            const issue_number = context.issue.number;
            const comment = 'This is a comment from the CI pipeline';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment
            });

    - name: Run shell script
      id: script
      run: |
          output=$(bash ./.github/scripts/degradation.sh)
          echo "::set-output name=output::$output"

    - name: Comment PR with script output
      uses: actions/github-script@v5
      with:
          script: |
            const issue_number = context.issue.number;
            const comment = `Script output: ${{ steps.script.outputs.output }}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment
            });
