name: honey singh

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  release:
    types: [published]
jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: critcmp
      run: |
        cargo install critcmp
        
    - name: Run benchmarks on main
      run: |
        cargo bench -- --save-baseline main

    - name: Run benchmarks on new
      run: |
        cargo bench -- --save-baseline new

    - name: Compare benchmarks and comment on PR
      run: |
        critcmp main new
