name: Benchmark Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
 benchmark:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Install Critcmp
     run: cargo install critcmp

   - name: Benchmark changes
     run: |
       cargo bench --bench impl_path_string_for_evaluation_context -- --save-baseline new_branch
       cargo bench --bench data_loader_bench -- --save-baseline new_branch
       cargo bench --bench request_template_bench -- --save-baseline new_branch
       cargo bench --bench json_like_bench -- --save-baseline new_branch

   - name: Fetch base branch
     run: git fetch

   - name: Checkout base branch
     run: git checkout ${{ github.base_ref }}

   - name: Benchmark base
     run: |
       cargo bench --bench impl_path_string_for_evaluation_context -- --save-baseline main_branch
       cargo bench --bench data_loader_bench -- --save-baseline main_branch
       cargo bench --bench request_template_bench -- --save-baseline main_branch
       cargo bench --bench json_like_bench -- --save-baseline main_branch


   - name: Compare benchmarks
     run: critcmp main_branch new_branch

   - name: Comment on issue
     uses: actions/github-script@v3
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       script: |
          output=$(/home/runner/.cargo/bin/critcmp base changes)
          echo "$output"
          awk 'NR > 2 {
              group=$1
              base=$7
              changes=$3
              gsub(/[^\-0-9\.]/, "", changes)
              gsub(/[^\-0-9\.]/, "", base)
              if (changes != "" && base != "") {
                  diff = changes - base
                  percentage = (diff / base) * 100
                  if (percentage > 10) {
                      printf "Percentage change for %s exceeds 10%%: %.2f%%\n", group, percentage
                      exit 1
                  }
              }
          }' <<< "$output"
