name: Benchmark Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install iai-callgrind-runner
      - name: Install iai-callgrind-runner
        run: cargo install --version 0.7.3 iai-callgrind-runner

      # Step 3: Install Valgrind
      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install valgrind


      - name: Execute build_time_compare.sh
        run: |
          chmod +x .github/scripts/compare_build_time.sh
          bash .github/scripts/compare_build_time.sh
