name: PR Files Changed

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR files
        uses: trilom/file-changes-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Display file changes
        run: |
          echo "Files changed: ${{ steps.file_changes.outputs.files }}"
          echo "Added files: ${{ steps.file_changes.outputs.added }}"
          echo "Modified files: ${{ steps.file_changes.outputs.modified }}"
          echo "Deleted files: ${{ steps.file_changes.outputs.deleted }}"

      - uses: actions/clubhouse-pr@v2
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          chToken: ${{ secrets.CLUBHOUSE_API_TOKEN
