name: Pull Request Changes

on:
  pull_request:
    paths:
      - '**/*'
jobs:
 build:
   runs-on: ubuntu-latest
   name: Test changed-files
   steps:
     - uses: actions/checkout@v2
     
     - name: list files
       run: |
         URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
         FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
         echo $FILES
       
     - name: Get file changes
       id: file_changes
       uses: trilom/file-changes-action@v1
       with:
         githubToken: ${{ secrets.GITHUB_TOKEN }}
