name: Pull Request Changes

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  find_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        run: |
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Set output
        id: set_output
        run: |
          echo "::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
          echo "Changed files: ${{ needs.find_changes.outputs.changed_files }}"
