name: PR Title Validation
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    outputs:
      SUGGESTED_TITLE: ${{ steps.suggest-title.outputs.SUGGESTED_TITLE }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          suggested_title="$type( suggested title: $SUGGESTED_TITLE"

      - name: Install rust-script
        run: |
          cargo install cargo-criterion rust-script

      - name: Check Degradation
        run: ./scripts/pr_name_check.rs
