name: PR Title Validation
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    outputs:
      env: 
        SUGGESTED_TITLE: ${{ steps.suggest-title.outputs.SUGGESTED_TITLE }}
    steps:
      - name: Check PR Title
        id: check-title
        uses: naveenk1223/action-pr-title@master
        with:
          regex: '^[a-zA-Z]+(\([a-zA-Z]+\))?: .+'
          allowed_prefixes: "feat,fix,docs,style,refactor,test,chore,ci,perf,revert"
          prefix_case_sensitive: false
          min_length: 1
          max_length: -1
          
      - name: Set Suggested Title
        id: suggest-title
        if: failure()
        run: echo "SUGGESTED_TITLE=feat(<optional_scope>): <title>" >> $GITHUB_ENV

  suggest-title:
    runs-on: ubuntu-latest
    needs: title-check
    steps:
      - name: Comment on PR with suggested title
        run: |
          echo "Suggested PR title: $SUGGESTED_TITLE"
          gh pr comment ${{ github.event.number }} --body "The PR title does not follow the required format. Consider using the following suggested title: $SUGGESTED_TITLE"
