name: Benchmark

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Extract file content
      id: extract-content
      run: echo "::set-output name=comment-body::Changes to the file:\n\`\`\`markdown\n$(cat a.txt)\n\`\`\`"

    - name: Comment on PR
      uses: peter-evans/commit-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: alankritdabral/tailcall
        edit-mode: append
        append-separator: newline
        reactions-edit-mode: append
        body: ${{ steps.extract-content.outputs.comment-body }}
