name: Benchmark

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: switching 
        run:
           git rev-parse -- abbrev-ref HEAD 
           git fetch origin "+refs/pull/${TRAVIS_PULL_REQUEST}/head:${TRAVIS_BRANCH}"
           git checkout ${TRAVIS_BRANCH}
           git rev-parse -- abbrev-ref HEAD

  Check_Degdratation:
    name: Criterion Benchmarks
    if: contains(github.event.pull_request.labels.*.name, 'benchmark')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Critcmp
        run: cargo install critcmp

      - name: Run Criterion on branch
        run: |
          cargo bench --features criterion -- --save-baseline new_branch

      - name: Fetch target branch
        run: |
          git fetch
          git checkout ${{ github.sha }}

      - name: Run Criterion on main
        run: |
          cargo bench --features criterion -- --save-baseline main_branch

      - name: Execute check_degradation.sh
        run: |
          bash .github/scripts/check_degradation.sh

      - name: Comment on PR
        uses: peter-evans/commit-comment@v3
        with:
          msg: |
            <details>
            <summary>Benchmark Results</summary>
            | Test                          | Base         | PR               | % change   |
            |-------------------------------|--------------|------------------|------------|
            $(cat benches/critcmp.txt)
            </details>
          token: ${{ secrets.GITHUB_TOKEN }}
