name: Benchmark

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: switching 
        run: |
           branch_name=$(git branch)
           echo $branch_name
           echo $(git checkout ${{ github.sha }})
           branch_name=$(git branch --show-current)
           echo $branch_name
