name: Switch Base Branch

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  switch-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        # Ensure we are in the correct directory
        cd $GITHUB_WORKSPACE

        # Set Git configuration
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

        # Extract target branch from the pull request context
        target_branch="${{ github.event.pull_request.base.ref }}"

        echo "Base branch: ${{ github.event.pull_request.base.ref }}"
        echo "Head branch: ${{ github.event.pull_request.head.ref }}"
        echo "Target branch: $target_branch"

        # Fetch the latest changes
        git fetch origin

        # Checkout the target branch
        git checkout $target_branch

        # Display the current branch for verification
        git branch
