name: commeent

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  commit_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add commit comment
        uses: peter-evans/commit-comment@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repository: alankritdabral/tailcall
          body-path: a.txt
          edit-mode: append
          append-separator: newline
          reactions-edit-mode: append
