name: Switch Base Branch

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get default branch
      id: get_branch
      run: |
        base_branch=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
        head_branch=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")

        echo "Base branch: $base_branch"
        echo "Head branch: $head_branch"
