name: Benchmark

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  commit_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add commit comment
        uses: peter-evans/commit-comment@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
