name: Benchmark

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run benchmark on"
        required: true
        default: "main"

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Comment on PR
      uses: peter-evans/commit-comment@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          Changes to the file:
          \`\`\`markdown
          ${{ steps.extract-content.outputs.file-content }}
          \`\`\`

    - name: Extract file content
      id: extract-content
      run: echo "::set-output name=file-content::$(cat a.txt)"
