name: commeent

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file content
        id: read-file
        run: |
          CONTENT=$(cat path/to/your/file.txt)
          echo "::set-output name=content::$CONTENT"

      - name: Add PR comment
        uses: peter-evans/commit-comment@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repository: alankritdabral/tailcall
          body-path: a.txt
          edit-mode: append
          append-separator: newline
          reactions-edit-mode: append
