name: commeent

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add PR comment
        uses: peter-evans/commit-comment@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repository: alankritdabral/tailcall
          body: "Your PR comment here"
