name: Compare Branches

on:
  pull:
    branches:
      - '*'

jobs:
  compare-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set base branch SHA
      run: echo "BASE_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Set target branch SHA
      run: echo "TARGET_SHA=$(git rev-parse ${{ env.TARGET_BRANCH }})" >> $GITHUB_ENV
      env:
        TARGET_BRANCH: ${{ env.TARGET_BRANCH }}

    - name: Switch to target branch
      run: git checkout ${{ env.TARGET_BRANCH }}
      if: env.TARGET_BRANCH != ''

    - name: Compare branch SHAs
      run: |
        echo "Base SHA: $BASE_SHA"
        echo "Target SHA: $TARGET_SHA"

        # Add your comparison logic here
        if [ "$BASE_SHA" == "$TARGET_SHA" ]; then
          echo "Branches are the same"
        else
          echo "Branches are different"
          # Add your additional logic for different branches
        fi
