name: Switch Base Branch

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get default branch
      id: get_branch
      run: |
        DEFAULT_BRANCH=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/branches" \
          | jq -r '.[] | select(.default == true) | .name')

        echo "Default branch is: $DEFAULT_BRANCH"
        echo "::set-output name=default_branch::$DEFAULT_BRANCH"

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.get_branch.outputs.default_branch }}
