name: Switch Base Branch

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  switch-base-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Switch Base Branch
        run: |
          PR_NUMBER=${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'workflow_run' && github.event.workflow_run.workflow == 'your-other-workflow' && github.event.workflow_run.head_branch }}
          BASE_BRANCH="your-new-base-branch"

          # Use the GitHub API to switch the base branch
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
            -d "{\"base\":\"${BASE_BRANCH}\"}"
