name: Build

on:
  push:
    branches:
      - "**"
    paths-ignore: ["docs/**", "**.md"]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
    paths-ignore: ["docs/**", "**.md"]
  release:
    types: [published]

jobs:
  draft_release:
    name: Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Current Branch (Fast)
        uses: actions/checkout@v4

        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: .github/release-drafter.yml
