name: Track Benchmark

on:
  push:
    paths-ignore: ["docs/**", "**.md"]
    branches:
      - main
  pull_request_target:
    paths-ignore: ["docs/**", "**.md"]
    branches:
      - main

jobs:
  track_benchmark_with_bencher:
    name: Track Benchmarks with Bencher
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    env:
      BASE_BENCHMARK_RESULTS: benches/track_benchmark.json
    steps:
      # - name: Check out code
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}

      # - name: Convert Cache into Proper Json
      #   run: |
      #     cat benches/main_benchmarks.json | jq -s 'map(select(.id and .mean and .slope and .median) | {id: .id, mean: .mean, slope: .slope, median: .median})' > benches/track_benchmark.json

      - name: Install Bencher CLI
        uses: bencherdev/bencher@main

      - name: Benchmark PR
        env:
          BENCHER_BRANCH: main
        run:  bencher run --project tailcall-1982174612 "$BASE_BENCHMARK_RESULTS"
