name: Track Benchmark

on:
    push:
      branches: main
    pull_request:
      paths-ignore: ["docs/**", "**.md"]
      types: [opened, reopened, synchronize, labeled]

jobs:
    benchmark_with_bencher:
      name: Continuous Benchmarking with Bencher
      runs-on: ubuntu-latest
      env:
        BENCHER_PROJECT: tailcall
        BENCHER_TESTBED: ubuntu-latest
        BENCHER_ADAPTER: json
        PR_BENCHMARK_RESULTS: benches/benchmarks.json 
        BASE_BENCHMARK_RESULTS: benches/main_benchmarks.json
        UPPER_BOUNDARY: 0.90
      steps:
        - name: Check out code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.sha }}

        - uses: bencherdev/bencher@main
            
        - name: Track base Benchmarks
          run: |

            export FEATURE_BRANCH=feature-branch-$(git rev-parse --short HEAD)
            
            bencher run \
            --token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhcGlfa2V5IiwiZXhwIjoxNzIwMDYyMTI4LCJpYXQiOjE3MTAwNjIxMjgsImlzcyI6ImJlbmNoZXIuZGV2Iiwic3ViIjoiZGFicmFsYWxhbmtyaXRAZ21haWwuY29tIiwib3JnIjpudWxsfQ.0QUtYqWgPtyYV8d6SsK2m4hNoa88r6aSI6Ojupatd3s\
            --file "$BASE_BENCHMARK_RESULTS"
