name: Track Benchmark

on:
    push:
      branches: main
    pull_request:
      paths-ignore: ["docs/**", "**.md"]
      types: [opened, reopened, synchronize, labeled]

jobs:
    benchmark_with_bencher:    
      name: Continuous Benchmarking with Bencher
      permissions:
        pull-requests: write
        contents: write
      runs-on: ubuntu-latest
      env:
        BENCHER_PROJECT: tailcall
        BENCHER_TESTBED: ubuntu-latest
        BENCHER_ADAPTER: json
        BASE_BENCHMARK_RESULTS: benches/main_benchmarks.json
      steps:
        - name: Check out code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.sha }}

        - uses: bencherdev/bencher@main
        - name: Track base Benchmarks
          run: |
            export BENCHER_API_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhcGlfa2V5IiwiZXhwIjoxNzIwMDYyMTI4LCJpYXQiOjE3MTAwNjIxMjgsImlzcyI6ImJlbmNoZXIuZGV2Iiwic3ViIjoiZGFicmFsYWxhbmtyaXRAZ21haWwuY29tIiwib3JnIjpudWxsfQ.0QUtYqWgPtyYV8d6SsK2m4hNoa88r6aSI6Ojupatd3s

            bencher run \
            --branch 'main' \
            --token "$BENCHER_API_TOKEN"\
            --ci-id '${{ github.event.pull_request.number }}' \
            --github-actions "${{ secrets.GITHUB_TOKEN }}" \
            --err \
            --file "$BASE_BENCHMARK_RESULTS"
